version: '3.8'
services:
  editor:
    build:
      context: ./editor
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_BASE_URL=http://localhost:4000
    depends_on:
      - editor-api

  editor-api:
    build:
      context: ./editor/server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
