name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: tpsappscriptingacr.azurecr.io
  IMAGE_API: app-scripting-editor-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- Build API (Node/Express) image ----
      # NOTE: Your API Dockerfile copies the SPA from ${REGISTRY}/app-scripting-editor:latest.
      # Make sure that image exists in ACR, or switch to the "self-contained" Dockerfile approach below.
      - name: Build & push API image (Node/Express + SPA)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile            # change if your API Dockerfile lives elsewhere
          push: true
          build-args: |
            REGISTRY=${{ env.REGISTRY }}
            VITE_APP_VERSION=1.0.0
            VITE_APP_BUILD_TIME=${{ github.event.head_commit.timestamp }}
            VITE_APP_COMMIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_API }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_API }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_API }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_API }}:buildcache,mode=max
